In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant(" World ")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
result

b'Hello  World '

In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [16]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [18]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [20]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [22]:
result

30

In [23]:
const = tf.constant(10)

In [24]:
fill_mat = tf.fill((4,4),10)

In [25]:
myzeros = tf.zeros((4,4))

In [26]:
myones = tf.ones((4,4))

In [27]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [28]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [30]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [31]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [33]:
with tf.Session() as sess:
    for op in my_ops:
        print(sess.run(op))
        print("\n")
        

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.5037521   0.49357074 -0.46985534 -1.1638919 ]
 [ 0.56826854 -0.8380369  -1.4631656  -0.123997  ]
 [-0.708288    0.4639509  -1.3598132   0.12173641]
 [ 1.0202796   0.0140103  -0.5313302  -0.39766747]]


[[0.1852082  0.87934375 0.35030985 0.03345311]
 [0.8509774  0.6733464  0.06244934 0.7858095 ]
 [0.79947805 0.09951675 0.83988583 0.21523368]
 [0.7424154  0.15340173 0.8542317  0.9993379 ]]




In [34]:
a = tf.constant([
    [1,2],
    [3,4]
])

In [36]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [38]:
b = tf.constant([[10],[100]])

In [43]:
b.get_shape()    

TensorShape([Dimension(2), Dimension(1)])

In [44]:
result = tf.matmul(a,b)

In [46]:
with tf.Session() as sess:
    result = sess.run(result)

In [49]:
result

array([[210],
       [430]], dtype=int32)